FROM quay.io/centos/centos:stream9
ARG UCX_VERSION
RUN yum install -y \
        autoconf \
        automake \
        gcc-c++ \
        git \
        glibc-devel \
        libtool \
        lsof \
        make \
        numactl-devel \
        rdma-core-devel \
        rpm-build \
        wget \
        && yum clean all

RUN dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
RUN yum install -y \
        cuda-compat-12-8 \
        cuda-driver-devel-12-8 \
        cuda-minimal-build-12-8 \
        cuda-nvrtc-devel-12-8 \
        libcufile-devel-12-8 \
        cuda-nvml-devel-12-8

WORKDIR /root
COPY build-ucx.sh /root/build-ucx.sh
RUN bash ./build-ucx.sh ${UCX_VERSION}
