name: docker build push
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-runner-set
    container:
      image: ubuntu:22.04
    steps:
      - name: install build tools
        run: |
          apt update
          apt install -y make git docker-compose curl ca-certificates
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc
          echo   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
                 $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt update
          apt install -y docker-ce
      - name: check out presto
        uses: actions/checkout@master
      - name: fix permissions
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: build image
        working-directory: ./test-build
        run: docker build -t 471112500371.dkr.ecr.us-west-2.amazonaws.com/test/runner-docker-build-push:latest .
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: push image
        run: docker push 471112500371.dkr.ecr.us-west-2.amazonaws.com/test/runner-docker-build-push:latest
