name: docker build push
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: check out presto
        uses: actions/checkout@master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: us-west-2
      - name: install aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
      - name: login ecr
        run: |      
          aws ecr get-login-password --region us-west-2
