name: docker build push
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: check out presto
        uses: actions/checkout@master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@main
        env:
          AWS_CONTAINER_CREDENTIALS_FULL_URI: ''
          AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: ''
