name: GDS test
on:
  workflow_dispatch:

jobs:
  GDS-test:
    runs-on: sally
    container:
      image: 471112500371.dkr.ecr.us-west-2.amazonaws.com/presto/gds-test:latest
      env:
        NVIDIA_GDS: enabled
      volumes:
        - /gpfs/zc2/gds:/gpds/zc2/gds
        - /etc/cufile.json:/etc/cufile.json:ro
      options: --runtime=nvidia --gpus all  --device /dev/infiniband/rdma_cm  --device=/dev/infiniband/uverbs0 --device=/dev/infiniband/uverbs1 --device=/dev/infiniband/uverbs2 --device=/dev/infiniband/uverbs3 --device=/dev/infiniband/uverbs4 --device=/dev/infiniband/uverbs5 --device=/dev/infiniband/uverbs6 --device=/dev/infiniband/uverbs7 --device=/dev/infiniband/uverbs8 --device=/dev/infiniband/uverbs9 --cap-add=IPC_LOCK
    steps:
    - run: | 
      gdscheck -p
      gdsio -f /gpfs/zc2/tmp/test2-0-sally -d 0 -w 10 -I 0 -s 100G -i 4M
