name: presto coordinator image
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: check out presto
        uses: actions/checkout@master
        with:
          repository: prestodb/presto
          ref: f5f0bb70c823669e0ff82a4f68c475432759e3be
      - name: install build tools
        run: |
          sudo apt update
          sudo apt install -y make git docker-compose curl ca-certificates
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
                 $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          sudo apt install -y docker-ce
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: us-west-2
      - name: install aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: login ecr
        run: |      
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 471112500371.dkr.ecr.us-west-2.amazonaws.com
      - name: pull dependency image
        run: docker pull 471112500371.dkr.ecr.us-west-2.amazonaws.com/presto/prestissimo-dependency-centos9:latest
      - name: build image
        run: |
          docker run -d --rm --name compile-presto-coordinator -v $(pwd):/presto 471112500371.dkr.ecr.us-west-2.amazonaws.com/presto/prestissimo-dependency-centos9:latest tail -f /dev/null
          docker exec compile-presto-coordinator bash -c "dnf install -y python3.11 && rm -f /usr/bin/python3 && ln -s /usr/bin/python3.11 /usr/bin/python3"
          docker exec compile-presto-coordinator bash -c "cd /presto && ./mvnw install -DskipTests -T 64 && chmod a+r presto-cli/target/presto-cli-0.295-SNAPSHOT-executable.jar"
          docker stop compile-presto-coordinator
          cp presto-server/target/presto-server-0.295-SNAPSHOT.tar.gz ./docker/
          cp presto-cli/target/presto-cli-0.295-SNAPSHOT-executable.jar ./docker/
          cd docker
          sed -i 's/dnf install -y java-17-openjdk less procps python3/dnf install -y java-17-openjdk less procps python3 which/' Dockerfile
          sed -i '/clean cache jobs/{N;d;}' Dockerfile
          sed -i 's/python \\$/python/' Dockerfile
          BUILDER=default PLATFORMS=linux/amd64 REG_ORG=471112500371.dkr.ecr.us-west-2.amazonaws.com/presto IMAGE_NAME=presto-coordinator bash ./build.sh 0.295-SNAPSHOT
      - name: tag and push image
        working-directory: ./presto-native-execution
        run: |
          export PRESTO_BUILD_IMG_TAG=$(date +%Y-%m-%d_%H%M)-$(git log --pretty="%h" | head -1)
          docker tag 471112500371.dkr.ecr.us-west-2.amazonaws.com/presto/presto-coordinator:latest 471112500371.dkr.ecr.us-west-2.amazonaws.com/presto/presto-coordinator:${PRESTO_BUILD_IMG_TAG}
          docker push 471112500371.dkr.ecr.us-west-2.amazonaws.com/presto/presto-coordinator:${PRESTO_BUILD_IMG_TAG}
          docker push 471112500371.dkr.ecr.us-west-2.amazonaws.com/presto/presto-coordinator:latest
