name: presto source from all repos
on:
  workflow_dispatch:
    inputs:
      presto-prs:
        description: 'Presto PRs to apply'
        required: true
        default: "25376,5135970"
      velox-prs:
        description: 'Velox PRs to apply'
        required: true
        default: "14640,d24f0ef 14462,0487b4c"
      lga-fork-branch:
        description: 'Branch to start Presto on the lga-fork'
        required: true
        default: velox_submodule

jobs:
  presto-gather:
    runs-on: arc-runner-set
    steps:
      - name: set timestamp
        run: echo $(date +%Y-%m-%d_%H%M) > /tmp/timestamp
      - name: check out presto
        uses: actions/checkout@master
        with:
          repository: lga-zurich/presto-exchange
          ref: velox_submodule
          path: presto
          fetch-depth: 0
      - name: install build tools
        run: |
          sudo apt update
          sudo apt install -y make git gh
      - name: set up git user
        run: |
          git config --global user.email "presto-cudf-ci@ibm.com"
          git config --global user.name "Presto CUDF CI"
      - name: get velox
        working-directory: ./presto/presto-native-execution
        run: |
          make submodules
          git remote -v
          git reflog
          cd velox
          git remote -v
          git reflog    
      - name: add presto repos
        working-directory: ./presto
        run: | 
          git remote add public https://github.com/prestodb/presto.git
          bash -c "for i in ${{ github.event.inputs.presto-prs }} ; { PR_NUM=\$(echo \$i | sed 's/\(.*\),.*/\1/') ; git fetch public pull/\${PR_NUM}/head:pr-\${PR_NUM} ; }"
      - name: rebase on presto PRs
        working-directory: ./presto
        run: |
          git switch -c ci-test-presto-$(cat /tmp/timestamp)
          bash -c "for i in ${{ github.event.inputs.presto-prs }} ; { PR_REF=\$(echo \$i | sed 's/.*,\(.*\)/\1/')  ; git rebase \${PR_REF} ; }"
      - name: add velox repos
        working-directory: ./presto/presto-native-execution/velox
        run: |
          git remote add public https://github.com/facebookincubator/velox.git
          bash -c "for i in ${{ github.event.inputs.velox-prs }} ; { PR_NUM=\$(echo \$i | sed 's/\(.*\),.*/\1/') ; git fetch public pull/\${PR_NUM}/head:pr-\${PR_NUM} ; }"
      - name: rebase on velox PRs
        working-directory: ./presto/presto-native-execution/velox
        run: |
          git switch -c ci-test-velox-$(cat /tmp/timestamp)
          bash -c "for i in ${{ github.event.inputs.velox-prs }} ; { PR_REF=\$(echo \$i | sed 's/.*,\(.*\)/\1/')  ; git rebase \${PR_REF} ; }"
      - name: push velox ci branch
        working-directory: ./presto/presto-native-execution/velox
        run: |
          git config --global url.https://${{ secrets.PRESTO_VELOX_PUSH_SECRET }}@github.com/.insteadOf https://github.com/
          git push --set-upstream origin ci-test-velox-$(cat /tmp/timestamp)
      - name: push presto ci branch
        working-directory: ./presto
        run: |
          git push --set-upstream origin ci-test-presto-$(cat /tmp/timestamp)
          