name: zoltan's playground
on:
  workflow_dispatch:

jobs:
  test:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    container:
      image: ubuntu:22.04
    steps:
      - name: install build tools
        run: |
          apt update
          apt install -y make git docker-compose
      - name: check out presto
        uses: actions/checkout@master
        with:
          repository: prestodb/presto
      - name: fix permissions
        uses: actions/checkout@v4
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: update velox
        run: |
          cd presto-native-execution
          make velox-submodule
      - name: disk space consumption before build
        run: df
      - name: build dependency image
        run: docker compose build centos-native-dependency
